export const START_GET_TRIAL_WINNER = "START_GET_TRIAL_WINNER";
export const SUCCESS_GET_TRIAL_WINNER = "SUCCESS_GET_TRIAL_WINNER";
export const FAIL_GET_TRIAL_WINNER = "FAIL_GET_TRIAL_WINNER";

export const UPDATE_PARTY = "UPDATE_PARTY";
